# Header
# navbar_brand: false
menu:
  home: index.html
  code: code/
  life: life/
  author: author/
  archives: archives/
menu_icon:
  home: castle
  code: bug
  life: bone
  author: danger
  archives: candy
rss: /atom.xml

# Content
excerpt_link: Read More

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
